[package]
name = "sunny-flowers-dwin-fork"
version = "1.0.0"
edition = "2021"
authors = [
    "Sophie <tileyratkins@gmail.com>",
    "Victor Roest <victor@xirion.net>"
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
serenity = { version = "0.10", features = [
    "client",
    "standard_framework",
    "voice",
    "unstable_discord_api",
    "collector"
]}
songbird = { version = "0.2.2", features = ["builtin-queue"] }
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread", "signal"] }
chrono = "0.4"
url = "2"
rand = {version = "0.8", features = ["small_rng"]}
once_cell = "1.8"

tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
reqwest = "0.11.13"
serde_json = "1.0.91"
rspotify = "0.11.6"
rspotify-model = "0.11.6"

[profile.release]
opt-level = 3
lto = true
