[package]
name = "sunny_flowers"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
serenity = { version = "0.10", features = [
    "client",
    "standard_framework",
    "voice",
]}
songbird = "0.2"
tokio = { version = "1.11", features = ["rt-multi-thread","time", "macros"] }